### ISSUE TITLE
Pupillometry analysis script unreachable

### ISSUE THREAD

**Issue by tombanfi** [pupil-labs/pupil-community#8]
The pupillometry analysis link returns a 404 page: [Eye Tracking Research Data Analysis](https://github.com/qalhata/Eye_Tracking_Research_Data_Analysis) - Python pupillometry analysis scripts to analyze pupil_data. 

Thank you for your great work!
Cheers

**Comment by papr** [comment]
@qalhata did you move the repository to https://github.com/qalhata/Eye-Tracking-Research-Fixation-EDA-PupilLabs-Data- or is this repository unrelated? If there is no response within 3 days I will remove the dead link from the list.

@tombanfi Based on the description in our README I am guessing that the original was deprecated and not compatible with the current version of Pupil Capture.

**Comment by qalhata** [comment]
@papr  @tombanfi  : My  apologies guys. I have been under a rock trying to complete my Thesis. with any luck I should submit that bad boy this weekend...  Phew!... #labouroflove. 

To answer the question. Yes indeed, the link papr refers to is the correct one.  I did move the work there indeed

@tombanfi I just dumped it there not thinking anyone would be interested in playing with it. But please do feel free to tweak to your heart's desire. I was thinking of perhaps building an add-on  for the software - to allow quick visualisations etc from within the software. @papr : do you think this is feasible?

Cheers guys.

**Comment by willpatera** [comment]
Updated with d6e0258ee3f3ed5080485820292799ac2aaaf551
